name: kwctl release
on:
  push:
    tags:
    - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    needs:
      - ci
    steps:
    - uses: actions/checkout@v2
    - uses: sigstore/cosign-installer@main
    - name: Sign kwctl
      run: cosign sign-blob Makefile
      env:
        COSIGN_EXPERIMENTAL: 1