name: kwctl release
on:
  push:
    tags:
    - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: sigstore/cosign-installer@main
    - name: Sign kwctl
      run: |
        Invoke-WebRequest -Uri "https://github.com/sigstore/cosign/releases/download/v1.8.0/cosign-windows-amd64.exe" -OutFile "cosign2"
        echo signing
        cosign --help
        echo finish
        cosign2 --help
      env:
        COSIGN_EXPERIMENTAL: 1