name: kwctl release
on:
  push:
    tags:
    - 'v*'
jobs:

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
    - run: Invoke-WebRequest -Uri https://github.com/sigstore/cosign/releases/download/v1.8.0/cosign-windows-amd64.exe -OutFile cosign2.exe
    - run: dir
    - name: Sign kwctl
      run: ./cosign2.exe sign-blob Makefile2
      env:
        COSIGN_EXPERIMENTAL: 1