name: kwctl release
on:
  push:
    tags:
    - 'v*'
jobs:

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: sigstore/cosign-installer@main
    - run: where cosign
    - run: Invoke-WebRequest -Uri https://github.com/sigstore/cosign/releases/download/v1.8.0/cosign-windows-amd64.exe -OutFile cosign3.exe
    - name: Sign kwctl
      run: ./cosign3.exe sign-blob Makefile > out.txt
      env:
        COSIGN_EXPERIMENTAL: 1
    - run: type out.txt