name: kwctl release
on:
  push:
    tags:
    - 'v*'
jobs:

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: raulcabello/cosign-installer@main
      with:
        cosign-release: 'v1.6.0' # optional
    - run: cosign version
