name: kwctl release
on:
  push:
    tags:
    - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:
  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
    - run: echo $HOME
    - run: dir $HOME
    - uses: actions/checkout@v2
    - uses: sigstore/cosign-installer@main
    - run: dir $HOME/.cosign
    - run: cosign --help
    - run: mv $HOME/.cosign/cosign $HOME/.cosign/cosign.exe
    - run: cosign.exe --help
